### ISSUE TITLE
Ajout des événements manquants

### ISSUE THREAD

**Issue by jillro** [jlm2017/campagne.jlm2017.fr#6]
Il manque:
- 5 juin 2016 - Défilé de la France insoumise à Paris : Ere du peuple, conditions de travail, environnement, candidature
- 28 août 2016 - Pique-nique de la France insoumise à Toulouse : Ecologie, pauvreté
- 27 septembre 2016 - Réunion publique à Boulogne-sur-Mer : pauvreté, économie de la mer, transition énergétique, jungle de Calais, Constitution
- 16 octobre 2016 - Discours à la Convention de la France insoumise à Lille : Ere du peuple
- 17 décembre 2016 - Réunion publique au Lamentin en Martinique : Economie de la mer, transition écologique

- [x] : trouver les vidéos sur la chaîne de JLM
- [x] : trouver les coordonnées géographiques
- [ ] : créer les pages

**Comment by spidersouris** [comment]
Vidéos YouTube :

5 juin 2016 : https://www.youtube.com/watch?v=zyEDOTEZyPM

28 août 2016 : https://www.youtube.com/watch?v=DJ8hQ77nbw8

27 septembre 2016 : https://www.youtube.com/watch?v=L0zosTKacRs

16 octobre 2016 : https://www.youtube.com/watch?v=-iC9UDYir8c

17 décembre 2016 : https://www.youtube.com/watch?v=4vhQIa0KAtw

**Comment by alexthevenot** [comment]
Coordonnées: 

5 juin 2016 : 48.883320, 2.369544 (Place Stalingrad, Paris)

28 août 2016 : 43.612232, 1.463004 (Jardin de l'observatoire, Toulouse)

27 septembre 2016 : 50.714193, 1.614494 (Espace de la Faïencerie, Boulogne-sur-Mer)

16 octobre 2016 : 50.643691, 3.061923 (?, Lille)

17 décembre 2016 : 14.622942, -60.991543 (Le Lamentin, Martinique)

**Comment by jillro** [comment]
Merci beaucoup ! Il ne reste plus qu'à créer les pages.

**Comment by alexthevenot** [comment]
J'ai tenté une PR : https://github.com/jlm2017/campagne.jlm2017.fr/pull/7
J'attends vos retours :)
